# Site settings
title: "WPGLP 调度SOP"
description: "WPLA13分拣仓调度标准作业程序"
baseurl: "/WPGLP"
url: "https://darrien-wang.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0

# Kramdown settings
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Darrien Wang"

# Disable service worker
webrick:
  headers:
    Service-Worker-Allowed: "/"

# Exclude files from processing
exclude:
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
