# Site settings
title: "WPGLP 仓库管理系统"
description: "WPLA13分拣仓调度和托盘回流管理标准作业程序"
baseurl: "/WPGLP"
url: "https://darrien-wang.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Darrien Wang"

# Disable automatic navigation
navigation: false
